//
//  DefaultColor.hpp
//  Tensor
//
//  Created by 陳均豪 on 2022/3/17.
//

#ifndef DefaultColor_h
#define DefaultColor_h

#include "GraphicAPI.hpp"

namespace otter {
namespace cv {

#define DefaultColor(c) \
    otter::cv::getDefaultColor(c)

enum DefaultColor {
    MAROON                  = 0,
    DARK_RED                = 1,
    BROWN                   = 2,
    FIREBRICK               = 3,
    CRIMSON                 = 4,
    RED                     = 5,
    TOMATO                  = 6,
    CORAL                   = 7,
    INDIAN_RED              = 8,
    LIGHT_CORAL             = 9,
    DARK_SALMON             = 10,
    SALMON                  = 11,
    LIGHT_SALMON            = 12,
    ORANGE_RED              = 13,
    DARK_ORANGE             = 14,
    ORANGE                  = 15,
    GOLD                    = 16,
    DARK_GOLDEN_ROD         = 17,
    GOLDEN_ROD              = 18,
    PALE_GOLDEN_ROD         = 19,
    DARK_KHAKI              = 20,
    KHAKI                   = 21,
    OLIVE                   = 22,
    YELLOW                  = 23,
    YELLOW_GREEN            = 24,
    DARK_OLIVE_GREEN        = 25,
    OLIVE_DRAB              = 26,
    LAWN_GREEN              = 27,
    CHARTREUSE              = 28,
    GREEN_YELLOW            = 29,
    DARK_GREEN              = 30,
    GREEN                   = 31,
    FOREST_GREEN            = 32,
    LIME                    = 33,
    LIME_GREEN              = 34,
    LIGHT_GREEN             = 35,
    PALE_GREEN              = 36,
    DARK_SEA_GREEN          = 37,
    MEDIUM_SPRING_GREEN     = 38,
    SPRING_GREEN            = 39,
    SEA_GREEN               = 40,
    MEDIUM_AQUA_MARINE      = 41,
    MEDIUM_SEA_GREEN        = 42,
    LIGHT_SEA_GREEN         = 43,
    DARK_SLATE_GRAY         = 44,
    TEAL                    = 45,
    DARK_CYAN               = 46,
    AQUA                    = 47,
    CYAN                    = 48,
    LIGHT_CYAN              = 49,
    DARK_TURQUOISE          = 50,
    TURQUOISE               = 51,
    MEDIUM_TURQUOISE        = 52,
    PALE_TURQUOISE          = 53,
    AQUA_MARINE             = 54,
    POWDER_BLUE             = 55,
    CADET_BLUE              = 56,
    STEEL_BLUE              = 57,
    CORN_FLOWER_BLUE        = 58,
    DEEP_SKY_BLUE           = 59,
    DODGER_BLUE             = 60,
    LIGHT_BLUE              = 61,
    SKY_BLUE                = 62,
    LIGHT_SKY_BLUE          = 63,
    MIDNIGHT_BLUE           = 64,
    NAVY                    = 65,
    DARK_BLUE               = 66,
    MEDIUM_BLUE             = 67,
    BLUE                    = 68,
    ROYAL_BLUE              = 69,
    BLUE_VIOLET             = 70,
    INDIGO                  = 71,
    DARK_SLATE_BLUE         = 72,
    SLATE_BLUE              = 73,
    MEDIUM_SLATE_BLUE       = 74,
    MEDIUM_PURPLE           = 75,
    DARK_MAGENTA            = 76,
    DARK_VIOLET             = 77,
    DARK_ORCHID             = 78,
    MEDIUM_ORCHID           = 79,
    PURPLE                  = 80,
    THISTLE                 = 81,
    PLUM                    = 82,
    VIOLET                  = 83,
    MAGENTA                 = 84,
    FUCHSIA                 = 85,
    ORCHID                  = 86,
    MEDIUM_VIOLET_RED       = 87,
    PALE_VIOLET_RED         = 88,
    DEEP_PINK               = 89,
    HOT_PINK                = 90,
    LIGHT_PINK              = 91,
    PINK                    = 92,
    ANTIQUE_WHITE           = 93,
    BEIGE                   = 94,
    BISQUE                  = 95,
    BLANCHED_ALMOND         = 96,
    WHEAT                   = 97,
    CORN_SILK               = 98,
    LEMON_CHIFFON           = 99,
    LIGHT_GOLDEN_ROD_YELLOW = 100,
    LIGHT_YELLOW            = 101,
    SADDLE_BROWN            = 102,
    SIENNA                  = 103,
    CHOCOLATE               = 104,
    PERU                    = 105,
    SANDY_BROWN             = 106,
    BURLY_WOOD              = 107,
    TAN                     = 108,
    ROSY_BROWN              = 109,
    MOCCASIN                = 110,
    NAVAJO_WHITE            = 111,
    PEACH_PUFF              = 112,
    MISTY_ROSE              = 113,
    LAVENDER_BLUSH          = 114,
    LINEN                   = 115,
    OLD_LACE                = 116,
    PAPAYA_WHIP             = 117,
    SEA_SHELL               = 118,
    MINT_CREAM              = 119,
    SLATE_GRAY              = 120,
    LIGHT_SLATE_GRAY        = 121,
    LIGHT_STEEL_BLUE        = 122,
    LAVENDER                = 123,
    FLORAL_WHITE            = 124,
    ALICE_BLUE              = 125,
    GHOST_WHITE             = 126,
    HONEYDEW                = 127,
    IVORY                   = 128,
    AZURE                   = 129,
    SNOW                    = 130,
    BLACK                   = 131,
    DIM_GRAY                = 132,
    GRAY                    = 133,
    DARK_GRAY               = 134,
    SILVER                  = 135,
    LIGHT_GRAY              = 136,
    GAINSBORO               = 137,
    WHITE_SMOKE             = 138,
    WHITE                   = 139
};

Color getDefaultColor(int color);

}   // end namespace cv
}   // end namespace otter

#endif /* DefaultColor_h */
